insert into public.companies (slug, name, legal_name, domain, domains, website, industry, hq_city, hq_country, aliases, source)
values
('amazon','Amazon','Amazon.com, Inc.','amazon.com',array['amazon.com','amazon.jobs'],'https://www.amazon.com','E-commerce & Cloud','Seattle','United States',array['AWS','Amazon Web Services'],'curated'),
('microsoft','Microsoft','Microsoft Corporation','microsoft.com',array['microsoft.com'],'https://www.microsoft.com','Technology','Redmond','United States',array['MSFT'],'curated'),
('meta','Meta','Meta Platforms, Inc.','meta.com',array['meta.com','facebook.com'],'https://www.meta.com','Technology','Menlo Park','United States',array['Facebook'],'curated'),
('google','Google','Google LLC','google.com',array['google.com'],'https://www.google.com','Technology','Mountain View','United States',array['Alphabet'],'curated'),
('apple','Apple','Apple Inc.','apple.com',array['apple.com'],'https://www.apple.com','Technology','Cupertino','United States',array[]::text[],'curated'),
('jpmorgan','JPMorganChase','JPMorgan Chase & Co.','jpmorganchase.com',array['jpmorganchase.com','jpmorgan.com','chase.com'],'https://www.jpmorganchase.com','Banking','New York','United States',array['JPMC','JP Morgan','Chase'],'curated'),
('goldman-sachs','Goldman Sachs','The Goldman Sachs Group, Inc.','goldmansachs.com',array['goldmansachs.com'],'https://www.goldmansachs.com','Banking','New York','United States',array['GS'],'curated'),
('morgan-stanley','Morgan Stanley','Morgan Stanley','morganstanley.com',array['morganstanley.com'],'https://www.morganstanley.com','Banking','New York','United States',array[]::text[],'curated'),
('citi','Citi','Citigroup Inc.','citi.com',array['citi.com','citigroup.com'],'https://www.citi.com','Banking','New York','United States',array['Citibank'],'curated'),
('bank-of-america','Bank of America','Bank of America Corporation','bankofamerica.com',array['bankofamerica.com','bofa.com'],'https://www.bankofamerica.com','Banking','Charlotte','United States',array['BofA'],'curated'),
('dbs','DBS Bank','DBS Group Holdings Ltd','dbs.com',array['dbs.com'],'https://www.dbs.com','Banking','Singapore','Singapore',array['DBS'],'curated'),
('ocbc','OCBC','Oversea-Chinese Banking Corporation Limited','ocbc.com',array['ocbc.com'],'https://www.ocbc.com','Banking','Singapore','Singapore',array['OCBC Bank'],'curated'),
('uob','UOB','United Overseas Bank Limited','uobgroup.com',array['uobgroup.com','uob.com.sg'],'https://www.uobgroup.com','Banking','Singapore','Singapore',array['United Overseas Bank'],'curated'),
('grab','Grab','Grab Holdings Limited','grab.com',array['grab.com'],'https://www.grab.com','Technology','Singapore','Singapore',array[]::text[],'curated'),
('sea','Sea','Sea Limited','sea.com',array['sea.com'],'https://www.sea.com','Technology','Singapore','Singapore',array['Sea Group'],'curated'),
('shopee','Shopee','Shopee Pte. Ltd.','shopee.com',array['shopee.com'],'https://www.shopee.com','E-commerce','Singapore','Singapore',array[]::text[],'curated'),
('bytedance','ByteDance','ByteDance Ltd.','bytedance.com',array['bytedance.com'],'https://www.bytedance.com','Technology','Beijing','China',array['ByteDance'],'curated'),
('tiktok','TikTok','TikTok Pte. Ltd.','tiktok.com',array['tiktok.com'],'https://www.tiktok.com','Technology','Singapore','Singapore',array[]::text[],'curated'),
('govtech-singapore','GovTech Singapore','Government Technology Agency of Singapore','tech.gov.sg',array['tech.gov.sg'],'https://www.tech.gov.sg','Public Technology','Singapore','Singapore',array['GovTech'],'curated'),
('singtel','Singtel','Singapore Telecommunications Limited','singtel.com',array['singtel.com'],'https://www.singtel.com','Telecommunications','Singapore','Singapore',array[]::text[],'curated'),
('st-engineering','ST Engineering','Singapore Technologies Engineering Ltd','stengg.com',array['stengg.com'],'https://www.stengg.com','Engineering','Singapore','Singapore',array[]::text[],'curated'),
('micron','Micron','Micron Technology, Inc.','micron.com',array['micron.com'],'https://www.micron.com','Semiconductors','Boise','United States',array[]::text[],'curated'),
('amd','AMD','Advanced Micro Devices, Inc.','amd.com',array['amd.com'],'https://www.amd.com','Semiconductors','Santa Clara','United States',array['Advanced Micro Devices'],'curated'),
('intel','Intel','Intel Corporation','intel.com',array['intel.com'],'https://www.intel.com','Semiconductors','Santa Clara','United States',array[]::text[],'curated'),
('nvidia','NVIDIA','NVIDIA Corporation','nvidia.com',array['nvidia.com'],'https://www.nvidia.com','Semiconductors','Santa Clara','United States',array[]::text[],'curated'),
('tesla','Tesla','Tesla, Inc.','tesla.com',array['tesla.com'],'https://www.tesla.com','Automotive & Energy','Austin','United States',array[]::text[],'curated'),
('deloitte','Deloitte','Deloitte Touche Tohmatsu Limited','deloitte.com',array['deloitte.com'],'https://www.deloitte.com','Consulting','London','United Kingdom',array[]::text[],'curated'),
('pwc','PwC','PricewaterhouseCoopers International Limited','pwc.com',array['pwc.com'],'https://www.pwc.com','Consulting','London','United Kingdom',array['PricewaterhouseCoopers'],'curated'),
('ey','EY','Ernst & Young Global Limited','ey.com',array['ey.com'],'https://www.ey.com','Consulting','London','United Kingdom',array['Ernst & Young'],'curated'),
('kpmg','KPMG','KPMG International Limited','kpmg.com',array['kpmg.com'],'https://www.kpmg.com','Consulting','London','United Kingdom',array[]::text[],'curated'),
('accenture','Accenture','Accenture plc','accenture.com',array['accenture.com'],'https://www.accenture.com','Consulting','Dublin','Ireland',array[]::text[],'curated'),
('mckinsey','McKinsey & Company','McKinsey & Company','mckinsey.com',array['mckinsey.com'],'https://www.mckinsey.com','Consulting','New York','United States',array['McKinsey'],'curated'),
('bcg','Boston Consulting Group','Boston Consulting Group, Inc.','bcg.com',array['bcg.com'],'https://www.bcg.com','Consulting','Boston','United States',array['BCG'],'curated'),
('bain','Bain & Company','Bain & Company, Inc.','bain.com',array['bain.com'],'https://www.bain.com','Consulting','Boston','United States',array['Bain'],'curated'),
('siemens','Siemens','Siemens AG','siemens.com',array['siemens.com'],'https://www.siemens.com','Industrial Technology','Munich','Germany',array[]::text[],'curated'),
('bmw','BMW Group','Bayerische Motoren Werke AG','bmwgroup.com',array['bmwgroup.com','bmw.com'],'https://www.bmwgroup.com','Automotive','Munich','Germany',array['BMW'],'curated'),
('bosch','Bosch','Robert Bosch GmbH','bosch.com',array['bosch.com'],'https://www.bosch.com','Engineering','Gerlingen','Germany',array['Robert Bosch'],'curated'),
('sap','SAP','SAP SE','sap.com',array['sap.com'],'https://www.sap.com','Enterprise Software','Walldorf','Germany',array[]::text[],'curated'),
('salesforce','Salesforce','Salesforce, Inc.','salesforce.com',array['salesforce.com'],'https://www.salesforce.com','Enterprise Software','San Francisco','United States',array[]::text[],'curated'),
('oracle','Oracle','Oracle Corporation','oracle.com',array['oracle.com'],'https://www.oracle.com','Enterprise Software','Austin','United States',array[]::text[],'curated'),
('ibm','IBM','International Business Machines Corporation','ibm.com',array['ibm.com'],'https://www.ibm.com','Technology','Armonk','United States',array['International Business Machines'],'curated'),
('cisco','Cisco','Cisco Systems, Inc.','cisco.com',array['cisco.com'],'https://www.cisco.com','Technology','San Jose','United States',array[]::text[],'curated'),
('adobe','Adobe','Adobe Inc.','adobe.com',array['adobe.com'],'https://www.adobe.com','Software','San Jose','United States',array[]::text[],'curated'),
('stripe','Stripe','Stripe, Inc.','stripe.com',array['stripe.com'],'https://www.stripe.com','Fintech','South San Francisco','United States',array[]::text[],'curated'),
('uber','Uber','Uber Technologies, Inc.','uber.com',array['uber.com'],'https://www.uber.com','Technology','San Francisco','United States',array[]::text[],'curated'),
('airbnb','Airbnb','Airbnb, Inc.','airbnb.com',array['airbnb.com'],'https://www.airbnb.com','Technology','San Francisco','United States',array[]::text[],'curated'),
('netflix','Netflix','Netflix, Inc.','netflix.com',array['netflix.com'],'https://www.netflix.com','Entertainment & Technology','Los Gatos','United States',array[]::text[],'curated'),
('spotify','Spotify','Spotify Technology S.A.','spotify.com',array['spotify.com'],'https://www.spotify.com','Audio & Technology','Stockholm','Sweden',array[]::text[],'curated'),
('anthropic','Anthropic','Anthropic PBC','anthropic.com',array['anthropic.com'],'https://www.anthropic.com','Artificial Intelligence','San Francisco','United States',array[]::text[],'curated'),
('openai','OpenAI','OpenAI, L.L.C.','openai.com',array['openai.com'],'https://www.openai.com','Artificial Intelligence','San Francisco','United States',array[]::text[],'curated'),
('deepseek','DeepSeek','Hangzhou DeepSeek Artificial Intelligence Co., Ltd.','deepseek.com',array['deepseek.com'],'https://www.deepseek.com','Artificial Intelligence','Hangzhou','China',array[]::text[],'curated'),
('tencent','Tencent','Tencent Holdings Limited','tencent.com',array['tencent.com'],'https://www.tencent.com','Technology','Shenzhen','China',array[]::text[],'curated'),
('alibaba','Alibaba','Alibaba Group Holding Limited','alibabagroup.com',array['alibabagroup.com','alibaba.com'],'https://www.alibabagroup.com','E-commerce & Cloud','Hangzhou','China',array['Alibaba Group'],'curated')
on conflict (slug) do update set
  name = excluded.name,
  legal_name = excluded.legal_name,
  domain = excluded.domain,
  domains = excluded.domains,
  website = excluded.website,
  industry = excluded.industry,
  hq_city = excluded.hq_city,
  hq_country = excluded.hq_country,
  aliases = excluded.aliases,
  source = excluded.source,
  updated_at = now();
