'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import Nav from '../../../components/Nav';
import { authFetch } from '../../../lib/authFetch';

function valid(v){return v?.status==='verified'&&(!v.verified_until||new Date(v.verified_until).getTime()>Date.now());}
function date(v){try{return new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(v));}catch{return '';}}

export default function UniversityVerificationPage(){
  const router=useRouter();
  const [universities,setUniversities]=useState([]);const [verifications,setVerifications]=useState([]);const [form,setForm]=useState({university:'',studentEmail:'',fieldOfStudy:'',graduationYear:''});const [verificationId,setVerificationId]=useState('');const [code,setCode]=useState('');const [devCode,setDevCode]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
  const load=async()=>{const [pr,ur]=await Promise.all([authFetch('/api/profile'),fetch('/api/universities?limit=150')]);const [pd,ud]=await Promise.all([pr.json(),ur.json()]);if(pr.status===401){router.replace('/login');return;}if(!pr.ok)throw new Error(pd.error||'Could not load your profile.');if(!pd.profile?.onboardingComplete){router.replace('/onboarding');return;}const list=Array.isArray(ud.universities)?ud.universities:[];setUniversities(list);setVerifications(pd.studentVerifications||[]);const u=pd.profile?.currentUniversity;setForm((f)=>({...f,university:u?.slug||list[0]?.slug||'',fieldOfStudy:pd.profile?.field_of_study||'',graduationYear:pd.profile?.graduation_year||''}));};
  useEffect(()=>{load().catch(e=>setMessage(e.message||'Could not load university verification.')).finally(()=>setLoading(false));},[]);
  const selected=useMemo(()=>universities.find(u=>u.slug===form.university),[universities,form.university]);
  const canEmailVerify=Boolean(selected?.domain||(selected?.domains||[]).length);
  const existing=useMemo(()=>selected?verifications.find(v=>v.university_id===selected.id):null,[verifications,selected]);const alreadyVerified=valid(existing);
  const start=async(e)=>{e.preventDefault();setBusy(true);setMessage('');try{const r=await authFetch('/api/student-verification/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,graduationYear:form.graduationYear?Number(form.graduationYear):null})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not start verification.');setVerificationId(d.verificationId);setDevCode(d.devCode||'');setMessage(`Code sent to your ${selected?.name||'university'} email.`);}catch(e){setMessage(e.message||'Could not start verification.');}finally{setBusy(false);}};
  const confirm=async(e)=>{e.preventDefault();setBusy(true);setMessage('');try{const r=await authFetch('/api/student-verification/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({verificationId,code})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Verification failed.');setMessage('✓ University verified. Your profile can now show a Verified Student badge.');setCode('');setDevCode('');await load();}catch(e){setMessage(e.message||'Verification failed.');}finally{setBusy(false);}};
  if(loading)return <><Nav/><main className="pageWrap verifyWrap"><div className="card emptyState">Loading university verification…</div></main></>;
  return <><Nav/><main className="pageWrap verifyWrap"><div className="pageTitle"><div><p className="eyebrow">PRIVATE TRUST LAYER</p><h1>Verify your university</h1><p>Prove student affiliation with a university-issued email. Your student email is never shown publicly or stored in plain text.</p></div></div>
    {existing&&<div className={`card verificationStatusCard ${alreadyVerified?'valid':existing.status}`}><div><span className="verificationStatusIcon">{alreadyVerified?'✓':existing.status==='pending'?'◷':'!'}</span></div><div><b>{existing.university?.name||selected?.name||'University'}</b><p>{alreadyVerified?`Verified student${existing.verified_until?` · valid until ${date(existing.verified_until)}`:''}.`:`Verification is ${existing.status}.`}</p></div></div>}
    {!verificationId?<form className="card reviewForm" onSubmit={start}><h2>{alreadyVerified?'University already verified':'Student email verification'}</h2><p>Use the email issued by your university. Verification lasts one year before re-checking.</p><label>University<select value={form.university} onChange={e=>setForm({...form,university:e.target.value})}>{universities.map(u=><option value={u.slug} key={u.slug}>{u.name}</option>)}</select></label>{!canEmailVerify&&selected&&<div className="authMessage">This university was added manually and does not have a verified email domain in LinkedOut yet. You can keep it on your profile, but student-email verification is unavailable until the directory is reviewed.</div>}<label>University email<input type="email" value={form.studentEmail} onChange={e=>setForm({...form,studentEmail:e.target.value})} placeholder={selected?.domain?`you@${selected.domain}`:'you@university.edu'} required disabled={alreadyVerified||!canEmailVerify}/></label><div className="formRow"><label>Field of study<input value={form.fieldOfStudy} onChange={e=>setForm({...form,fieldOfStudy:e.target.value})} placeholder="Computer Science" disabled={alreadyVerified}/></label><label>Graduation year<input type="number" min="1950" max="2100" value={form.graduationYear} onChange={e=>setForm({...form,graduationYear:e.target.value})} placeholder="2029" disabled={alreadyVerified}/></label></div>{message&&<div className="authMessage">{message}</div>}{alreadyVerified?<div className="verificationDoneActions"><Link className="button primary" href="/">Enter LinkedOut</Link><Link className="button secondary" href="/profile">View profile</Link></div>:<button className="button primary submit" disabled={busy||!canEmailVerify}>{busy?'Sending…':'Send university code'}</button>}</form>:
    <form className="card reviewForm" onSubmit={confirm}><h2>Enter your code</h2><p>The code expires after 10 minutes and allows five attempts.</p>{devCode&&<div className="devCode">Local-dev code: <b>{devCode}</b></div>}<label>6-digit code<input inputMode="numeric" maxLength="6" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000" required/></label>{message&&<div className="authMessage">{message}</div>}<button className="button primary submit" disabled={busy||code.length!==6}>{busy?'Checking…':'Verify university'}</button><button className="authSwitch" type="button" onClick={()=>{setVerificationId('');setCode('');setMessage('')}}>Start over</button></form>}
    <div className="verifyFoot"><Link href="/verify">Verify a workplace instead</Link><span> · </span><Link href="/profile">Back to profile</Link></div>
  </main></>;
}
